name: Build and Push Python Hello World Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'python-app/**' # Only trigger if changes are made in the python-app directory
      - '.github/workflows/build-python-app.yml' # Also trigger if the workflow itself changes
  workflow_dispatch:

env:
  IMAGE_NAME: python-app

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          cache: true

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./python-app
          push: false
          load: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ github.event.repository.pushed_at }}
            org.opencontainers.image.revision=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: List built images (for verification)
        run: docker images
