name: Verify Kubernetes Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  verify-runner:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code (optional, but good practice)
        uses: actions/checkout@v4

      - name: Display Runner Hostname and User
        run: |
          echo "Running on host: $(hostname)"
          echo "Running as user: $(whoami)"
          echo "Current working directory: $(pwd)"
